name: Build GoKi App

on:
  push:
    branches: [ main ]


jobs:

    build:
        name: Build
        strategy:
            matrix:
                go-version: [1.21.x]
                platform: [ubuntu-latest]
        runs-on: ${{ matrix.platform }}
        steps:

        - name: Install Go
          uses: actions/setup-go@v2
          with:
                go-version: ${{ matrix.go-version }}

        - name: Install GoKi
          run: go install goki.dev/goki@latest

        - name: Build Demo
          run: goki build demo -o static/demo -t js